name: PR Test Server

on:
  pull_request:
    branches: [main, dev]

jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout node
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Server dependencies
        run: |
          cd server
          npm ci

      - name: Run tests
        run: |
          cd server
          npm run test
